/*
 * This file defines the RootLayout component for a Next.js application.
 * It sets global metadata, imports necessary styles, and configures the Inter font.
 * The RootLayout component wraps the entire application, ensuring that all pages
 * share a consistent layout and style. The metadata provides SEO benefits and the
 * font configuration ensures a uniform typography throughout the app.
 */

// Importing types for Metadata from Next.js
import type { Metadata } from "next";

// Importing the Inter font from Google Fonts through Next.js
import { Inter } from "next/font/google";

// Importing global styles
import "../styles/globals.css";
import Navbar from "@/components/Navbar";

// Setting up the Inter font with the specified subset
const inter = Inter({ subsets: ["latin"] });

// Defining metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Defining the RootLayout component
// This component wraps the entire application and applies global settings
export default function RootLayout({
  // Destructuring children from props
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Setting the language of the document to English
    <html lang="en">
      {/* Applying the Inter font to the body and rendering children components */}
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
