import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col bg-gray-100`}>
        {/* Navbar at the top */}
        <Navbar />

        {/* Scrollable content below the navbar */}
        <main className="flex-1 overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
