version: '3.8'

services:
  backend:
    build: backend/.
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: main.py

  http_server:
    build: frontend/.
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
